export const contentData = [
  {
    title: "Cotton Comfort T-shirt",
    category: "T-shirts & Tops",
    images: [
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
    ],
    price: "35.99",
    description: ['100% combed ringspun cotton', 'Double-needle stitching', 'Made in USA'],
    colors: ["white", "DimGray", ],
    sizes: ["M", "L", "XL", "XXL", "3XL"],
    id: new Date().getTime() + Math.random(1, 1000000000),

    sale: "25.99",
    bestseller: true,
  },
  {
    title: "Classic Crew Neck T-shirt",
    category: "T-shirts & Tops",
    images: [
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
    ],
    price: "29.99",
    description: ['Soft and lightweight fabric', 'Versatile for any occasion'],
    colors: ["black", "burlyWood"],
    sizes: ["M", "L", "XL"],
    id: new Date().getTime() + Math.random(1, 1000000000),

    sale: "22.49",
    bestseller: true,
  },
  {
    title: "Casual V-Neck T-shirt",
    category: "T-shirts & Tops",
    images: [
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
    ],
    price: "25.99",
    description: ['Cool and breathable fabric', 'Perfect for everyday wear'],
    colors: ["white", "DimGray", "DarkGreen",],
    sizes: ["S", "M", "L", "XL", "XXL"],
    id: new Date().getTime() + Math.random(1, 1000000000),
  },
  {
    title: "Athletic Performance T-shirt",
    category: "T-shirts & Tops",
    images: [
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
    ],
    price: "39.99",
    description: ['Moisture-wicking fabric', 'Great for workouts and sports'],
    colors: ["black", "MediumBlue", "orange"],
    sizes: ["S", "M", "XL"],
    id: new Date().getTime() + Math.random(1, 1000000000),
  },
  {
    title: "Basic Pullover Hoodie",
    category: "Hoodies",
    images: [
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
    ],
    price: "49.99",
    description: ['Warm and comfortable fleece', 'Front kangaroo pocket'],
    colors: [ "DimGray", "maroon"],
    sizes: ["S", "M", "L", "XXL"],
    id: new Date().getTime() + Math.random(1, 1000000000),

    sale: "39.99",
    bestseller: true,
  },
  {
    title: "Sporty Zip-Up Hoodie",
    category: "Hoodies",
    images: [
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
    ],
    price: "59.99",
    description: ['Stylish and functional design', 'Full-zip front with drawstrings'],
    colors: ["black", "DimGray", "DarkMagenta" ],
    sizes: ["S", "M", "L"],
    id: new Date().getTime() + Math.random(1, 1000000000),
  },
  {
    title: "Slim Fit Pullover Hoodie",
    category: "Hoodies",
    images: [
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
    ],
    price: "45.99",
    description: ['Modern slim fit', 'Soft cotton blend'],
    colors: ["DimGray", "MediumBlue", "black"],
    sizes: ["S", "M", "L", "XL"],
    id: new Date().getTime() + Math.random(1, 1000000000),

    sale: "35.99",
    bestseller: true,
  },
  {
    title: "Classic Denim Shirt",
    category: "Shirts",
    images: [
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
    ],
    price: "59.99",
    description: ['Authentic denim look', 'Button-up front'],
    colors: ["MediumBlue"],
    sizes: ["S", "M", "L", "XL"],
    id: new Date().getTime() + Math.random(1, 1000000000),
  },
  {
    title: "Flannel Plaid Shirt",
    category: "Shirts",
    images: [
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
      ["item-img.avif", "item-img.avif", "item-img.avif"],
    ],
    price: "39.99",
    description: ['Cozy flannel fabric', 'Classic plaid pattern'],
    colors: [ "MediumBlue", "DarkGreen"],
    sizes: ["S", "M", "L", "XL"],
    id: new Date().getTime() + Math.random(1, 1000000000),

    sale: "29.99",
  },
];
